name: Run security tests on .NET Core app

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    #Not currently publishing to Azure, commenting out
    #- uses: azure/appservice-actions/webapp@master
    #  with:
    #    app-name: dotnetcorewebapp19
    #    publish-profile: ${{ secrets.publish_profile }}
    #    package: "bin/Release/netcoreapp3.0"



    # This works, commented out so it doesn't break the build.
    #- name: Run Snyk to check for vulnerabilities
    #  uses: snyk/actions/dotnet@master
    #  env:
    #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  #This works, but it's a person's personal repo, which means RISK.    
  gitleak:
    name: gitleaks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: docker pull zricethezav/gitleaks
      - uses: fmigneault/gitleaks-action@master
      - uses: CySeq/gitcret@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



  #Trying to run basic trufflehog scan to look for secrets
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@custom-rules
      #- uses: actions/upload-artifact@v1
       # name: trufflehogreport
        #path: reports 
  

   # broken
   #Adding Secret-scan from Github staff
   #   -  name: Secret Scan
   #      uses: max/secret-scan@1.0.0

           
    
    #This works. However. my azure instance is down right now, so let's skip it.
    # dotnet build and publish
    #- name: Build with dotnet
    #  run: dotnet build --configuration Release
    #- name: dotnet publish
    #  run: |
    #    dotnet publish -c Release -o dotnetcorewebapp 
    #- name: 'Run Azure webapp deploy action using publish profile credentials'
    #  uses: azure/webapps-deploy@v1
    #  with: 
    #    app-name: dotnetcorewebapp19 # Replace with your app name
    #    publish-profile: ${{ secrets.publish_profile }} # Define secret variable in repository settings as per action documentation
    #    package: './dotnetcorewebapp' 
