name: Tanya's .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:  3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Trufflehog Actions Scan
      uses: edplato/trufflehog-actions-scan@v0.9h-beta
      with:
        scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json" # Add custom options here*
