name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    #Not currently publishing to Azure, commenting out
    #- uses: azure/appservice-actions/webapp@master
    #  with:
    #    app-name: dotnetcorewebapp19
    #    publish-profile: ${{ secrets.publish_profile }}
    #    package: "bin/Release/netcoreapp3.0"



    # This works, commented out so it doesn't break the build.
    #- name: Run Snyk to check for vulnerabilities
    #  uses: snyk/actions/dotnet@master
    #  env:
    #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # This does not work, yet.
    #https://github.com/sonatype-nexus-community/nancy-github-action 
    #- name: Nancy
    #  uses: sonatype-nexus-community/nancy-github-action@master
    #  with:
    #    target: go.sum


    # This does not work, yet.
    #Adding GitLeaks
    #- name: gitleaks-action
    #  uses: eshork/gitleaks-action@v1.0.0
      
  # ref: https://github.com/svdarren/secrets-workflow/blob/9633bc1195a1ca1d4d70415aa4eff6cf55d706de/.github/workflows/secrets.yml
  gitleak:
    name: gitleaks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: docker pull zricethezav/gitleaks
      #- run: |
      #    docker run --name=gitleaks --volume $GITHUB_WORKSPACE:/workspace/ \
      #    -v --exclude-forks --redact --threads=1 --branch=$GITHUB_REF --repo-path=/workspace/
      #- run: docker run --rm --name=gitleaks -v /tmp/:/code/ zricethezav/gitleaks -v --repo-path=/code/gitleaks
      # @todo command is failing
      #- run: gitleaks -v --exclude-forks --redact --threads=1 --branch=$GITHUB_REF --repo-path=$GITHUB_WORKSPACE

      - uses: fmigneault/gitleaks-action@master
      - uses: CySeq/gitcret@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


   # This does not work, yet.
   #Adding Secret-scan from Github staff
   # - name: Secret Scan
   #   uses: max/secret-scan@1.0.0

  
   

    # This runs successfully but does not provide useful results
    #Scan OSS - open source security issues
    #- name: sast-scan
    #  uses: AppThreat/sast-scan-action@1.0.2
    #- uses: actions/upload-artifact@v1
    #  with:
    #    name: SASTreports
    #    path: reports
    
    # This runs successfully but can't seem to find the dependencies file
    #Security audit of dependencies 
    #- uses: AppThreat/dep-scan-action@master
    #  env:
    #    VULNDB_HOME: ${{ github.workspace }}/db
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #- uses: actions/upload-artifact@v1
    #  with:
    #    name: DEPreports
    #    path: reports
    
    #This works. However. my azure instance is down right now, so let's skip it.
    # dotnet build and publish
    #- name: Build with dotnet
    #  run: dotnet build --configuration Release
    #- name: dotnet publish
    #  run: |
    #    dotnet publish -c Release -o dotnetcorewebapp 
    #- name: 'Run Azure webapp deploy action using publish profile credentials'
    #  uses: azure/webapps-deploy@v1
    #  with: 
    #    app-name: dotnetcorewebapp19 # Replace with your app name
    #    publish-profile: ${{ secrets.publish_profile }} # Define secret variable in repository settings as per action documentation
    #    package: './dotnetcorewebapp' 
